USER_DATA = {}

ACTIVE_DUELS = {}
HIGHLOW_DUELS = {}
BLACKJACK_GAMES = {}
WORDLE_GAMES = {}
MASTERMIND_GAMES = {}
QUIZ_GAMES = {}
QUIZ_DUELS_1V1 = {}
GHIGLIOTTINA_DUELS = {}
HEIST_GAMES = {}
PENITENZE_ATTIVE = {}
TIC_TAC_TOE_GAMES = {}
DAILY_DONATIONS = set()

ACTIVE_TITLES = {}
ACTIVE_PERSECUTE = {}
USER_INVENTORIES = {}

FLAGS = {"troll": False}
